# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
timezone:            Europe/London
locale:              en_gb
name:				         my blog.
title:               witko knows best
tagline:             'tagline'
description:         'description'
url:                 https://adamwitko.github.io
rss:                 https://adamwitko.github.io/feed.xml
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              witko

author:
  name:           	 Adam Witko
  url:            	 https://adamwitko.github.io
  twitter:           firagabeatsrock
  linkedin:          adamwitko
  informal_name:     Adam

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9955

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
